name: Maven Package

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 and configure settings.xml
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: 'github'                # deve bater com <distributionManagement><repository><id> no pom.xml
          server-username: '${{ github.actor }}'
          server-password: '${{ secrets.GITHUB_TOKEN }}'
          settings-path: '${{ github.workspace }}'  # irá criar ${GITHUB_WORKSPACE}/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to GitHub Packages
        run: mvn -B deploy --settings "${{ github.workspace }}/settings.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}